//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIhotel.Models.Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cancelacion
    {
        public int id_cancelacion { get; set; }
        public int id_reserv_cancelacion { get; set; }
        public System.DateTime fecha_cancelacion { get; set; }
        public string motivo_cancelacion { get; set; }
        public string creado_por_cancelacion { get; set; }
        public string estado_cancelacion { get; set; }
        public string mod_por_cancelacion { get; set; }
        public System.DateTime fecha_mod_cancelacion { get; set; }
    
        public virtual reservacion reservacion { get; set; }
    }
}
