//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIhotel.Models.Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE()
        {
            this.NOTA_CREDITO_CLIENTE = new HashSet<NOTA_CREDITO_CLIENTE>();
            this.reservacions = new HashSet<reservacion>();
        }
    
        public string ID_CLIENTE { get; set; }
        public string ID_TERCERO_CLIENTE { get; set; }
        public string ID_T_CLIENTE { get; set; }
        public decimal LIM_CRED_CLIENTE { get; set; }
        public decimal SALDO_CLIENTE { get; set; }
        public string ESTADO_CLIENTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTA_CREDITO_CLIENTE> NOTA_CREDITO_CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservacion> reservacions { get; set; }
        public virtual TIPO_CLIENTE TIPO_CLIENTE { get; set; }
        public virtual Tercero Tercero { get; set; }
    }
}
