//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIhotel.Models.Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class habitacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public habitacion()
        {
            this.mantenimientoes = new HashSet<mantenimiento>();
            this.alojamientoes = new HashSet<alojamiento>();
        }
    
        public string id_habitacion { get; set; }
        public string descr_habitacion { get; set; }
        public string t_habitacion { get; set; }
        public string edificio_habitacion { get; set; }
        public int piso_habitacion { get; set; }
        public string estado_habitacion { get; set; }
    
        public virtual edificio edificio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mantenimiento> mantenimientoes { get; set; }
        public virtual tipo_habitacion tipo_habitacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alojamiento> alojamientoes { get; set; }
    }
}
