//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIhotel.Models.Hotel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hotelEntities : DbContext
    {
        public hotelEntities()
            : base("name=hotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alojamiento> alojamientoes { get; set; }
        public virtual DbSet<cama> camas { get; set; }
        public virtual DbSet<cancelacion> cancelacions { get; set; }
        public virtual DbSet<caracteristica> caracteristicas { get; set; }
        public virtual DbSet<CLIENTE> CLIENTEs { get; set; }
        public virtual DbSet<DIRECCION> DIRECCIONs { get; set; }
        public virtual DbSet<edificio> edificios { get; set; }
        public virtual DbSet<EMAIL> EMAILs { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADOes { get; set; }
        public virtual DbSet<habitacion> habitacions { get; set; }
        public virtual DbSet<HOTEL> HOTELs { get; set; }
        public virtual DbSet<mantenimiento> mantenimientoes { get; set; }
        public virtual DbSet<mantenimiento_det> mantenimiento_det { get; set; }
        public virtual DbSet<MUNICIPIO> MUNICIPIOs { get; set; }
        public virtual DbSet<NOTA_CREDITO_ABONO> NOTA_CREDITO_ABONO { get; set; }
        public virtual DbSet<NOTA_CREDITO_CLIENTE> NOTA_CREDITO_CLIENTE { get; set; }
        public virtual DbSet<NOTA_CREDITO_DETALLE> NOTA_CREDITO_DETALLE { get; set; }
        public virtual DbSet<Oferta> Ofertas { get; set; }
        public virtual DbSet<oferta_det_01> oferta_det_01 { get; set; }
        public virtual DbSet<oferta_det_02> oferta_det_02 { get; set; }
        public virtual DbSet<oferta_det_03> oferta_det_03 { get; set; }
        public virtual DbSet<PAI> PAIS { get; set; }
        public virtual DbSet<Permisos_Adi> Permisos_Adi { get; set; }
        public virtual DbSet<PROVINCIA> PROVINCIAs { get; set; }
        public virtual DbSet<reservacion> reservacions { get; set; }
        public virtual DbSet<reservacion_det> reservacion_det { get; set; }
        public virtual DbSet<servicio> servicios { get; set; }
        public virtual DbSet<TELEFONO> TELEFONOes { get; set; }
        public virtual DbSet<TEMPORADA> TEMPORADAs { get; set; }
        public virtual DbSet<Tercero> Terceroes { get; set; }
        public virtual DbSet<thabitacion_cama> thabitacion_cama { get; set; }
        public virtual DbSet<tipo_alojamiento> tipo_alojamiento { get; set; }
        public virtual DbSet<tipo_archivo> tipo_archivo { get; set; }
        public virtual DbSet<TIPO_CLIENTE> TIPO_CLIENTE { get; set; }
        public virtual DbSet<TIPO_EMPLEADO> TIPO_EMPLEADO { get; set; }
        public virtual DbSet<tipo_habitacion> tipo_habitacion { get; set; }
        public virtual DbSet<Tipo_Identificacion> Tipo_Identificacion { get; set; }
        public virtual DbSet<tipo_mantenimiento> tipo_mantenimiento { get; set; }
        public virtual DbSet<Tipo_Usuario> Tipo_Usuario { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<archivo> archivoes { get; set; }
    }
}
