//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIhotel.Models.Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOTEL
    {
        public string id_hotel { get; set; }
        public string descr_hotel { get; set; }
        public string Direccion_hotel { get; set; }
        public string tel_hotel { get; set; }
        public string a_cancelacion_hotel { get; set; }
    }
}
