//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIhotel.Models.Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class mantenimiento_det
    {
        public int id_mantenimiento_det { get; set; }
        public string id_t_mant_det { get; set; }
        public string id_empleado_det { get; set; }
        public string estado_mantenimiento { get; set; }
    
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual mantenimiento mantenimiento { get; set; }
        public virtual tipo_mantenimiento tipo_mantenimiento { get; set; }
    }
}
