//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIhotel.Models.Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class mantenimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mantenimiento()
        {
            this.mantenimiento_det = new HashSet<mantenimiento_det>();
        }
    
        public int id_mantenimiento { get; set; }
        public string id_hab_mantenimiento { get; set; }
        public System.DateTime fecha_cre_mantenimiento { get; set; }
        public System.DateTime fecha_mod_mantenimiento { get; set; }
        public string estado_mantenimiento { get; set; }
    
        public virtual habitacion habitacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mantenimiento_det> mantenimiento_det { get; set; }
    }
}
