//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIhotel.Models.Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTA_CREDITO_CLIENTE
    {
        public int ID_NCC { get; set; }
        public string ID_CLIENTE_NCC { get; set; }
        public decimal MONTO_NCC { get; set; }
        public System.DateTime FECHA_NCC { get; set; }
        public string ESTADO_NCC { get; set; }
        public string CREADO_P_NCC { get; set; }
        public System.DateTime FECHA_C_NCC { get; set; }
        public string MOD_P_NCC { get; set; }
        public System.DateTime FECHA_M_NCC { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
