//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIhotel.Models.Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class oferta_det_01
    {
        public string id_oferta_det01 { get; set; }
        public string id_t_aloj_det01 { get; set; }
        public decimal descuento_det01 { get; set; }
    
        public virtual Oferta Oferta { get; set; }
        public virtual tipo_alojamiento tipo_alojamiento { get; set; }
    }
}
