//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIhotel.Models.Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reservacion()
        {
            this.alojamientoes = new HashSet<alojamiento>();
            this.cancelacions = new HashSet<cancelacion>();
            this.NOTA_CREDITO_ABONO = new HashSet<NOTA_CREDITO_ABONO>();
            this.NOTA_CREDITO_DETALLE = new HashSet<NOTA_CREDITO_DETALLE>();
            this.reservacion_det = new HashSet<reservacion_det>();
        }
    
        public int id_reservacion { get; set; }
        public string id_cliente { get; set; }
        public string id_t_aloj_reservacion { get; set; }
        public System.DateTime fecha_lleg_reservacion { get; set; }
        public System.DateTime fecha_sal_reservacion { get; set; }
        public decimal Monto_apagar { get; set; }
        public string estado_reservacion { get; set; }
        public string creado_por_reservacion { get; set; }
        public System.DateTime fecha_cre_reservacion { get; set; }
        public string mod_por_reservacion { get; set; }
        public System.DateTime fecha_mod_reservacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alojamiento> alojamientoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cancelacion> cancelacions { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTA_CREDITO_ABONO> NOTA_CREDITO_ABONO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTA_CREDITO_DETALLE> NOTA_CREDITO_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservacion_det> reservacion_det { get; set; }
        public virtual tipo_alojamiento tipo_alojamiento { get; set; }
    }
}
