//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIhotel.Models.Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TELEFONO
    {
        public string id_Tercero_Tel { get; set; }
        public string Numero_Tel { get; set; }
        public string TIPO_Tel { get; set; }
        public int N_LINEA_Tel { get; set; }
        public string ESTADO_Tel { get; set; }
    
        public virtual Tercero Tercero { get; set; }
    }
}
