//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIhotel.Models.Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Permisos_Adi = new HashSet<Permisos_Adi>();
        }
    
        public string id_Usuario { get; set; }
        public string id_Tercero_Usuario { get; set; }
        public int Tipo_Usuario { get; set; }
        public string password_Usuario { get; set; }
        public string Estado_Usuario { get; set; }
    
        public virtual Tercero Tercero { get; set; }
        public virtual Tipo_Usuario Tipo_Usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Permisos_Adi> Permisos_Adi { get; set; }
    }
}
